/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:  ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        mono:  ['Space Mono', 'monospace'],
      },
      colors: {
        'ivory':          '#FDFAF4',
        'ivory-2':        '#F8F3E8',
        'ivory-3':        '#F0EAD8',
        'ivory-4':        '#E8DECA',
        'cream':          '#EAE4DA',
        'cream-2':        '#E3DCD2',
        'cream-3':        '#DAD2C5',
        'cream-4':        '#CFC6B7',
        'sand':           '#E8DCC8',
        'champagne':      '#F0E0B0',
        'champagne-2':    '#E8D5A3',
        'walnut':         '#2C1A0E',
        'walnut-2':       '#3D2415',
        'walnut-3':       '#4E2F1A',
        'walnut-mid':     '#7A5C42',
        'walnut-light':   '#A8845F',
        'walnut-pale':    '#D4B898',
        'gold':           '#C9A84C',
        'gold-dark':      '#9B7A28',
        'gold-mid':       '#B8943E',
        'gold-light':     '#E8D5A3',
        'gold-pale':      '#F5EDD8',
        'smoke':          '#F5F4F2',
        'smoke-2':        '#EDECE9',
        'smoke-3':        '#E3E2DD',
        'jet':            '#0C0C0C',
        'jet-mid':        '#3D3D3D',
        'jet-light':      '#6E6E6E',
        'silver':         '#9A9A9A',
        'pearl':          '#FAFAF9',
        'warm-white':     '#FFFCF5',
      },
      animation: {
        'marquee':        'marquee 35s linear infinite',
        'marquee-slow':   'marquee 55s linear infinite',
        'float':          'float 6s ease-in-out infinite',
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-12px)' },
        },
      },
    },
  },
  plugins: [],
}
